# The main config file for your Jekyll template

# Site settings
title: Media and Materiality               # used for the html title of every page
desc: >
  Course site for Media and Materiality: From Marx to Barad graduate seminar at the University of Victoria (Fall 2016), taught by Jentery Sayers

url: https://jentery.github.io      # put your website hosting url here
baseurl: '/cspt500'                 # the subpath of your site, e.g. /blog
permalink: /:title/   # how should we display posts url

# Meta settings
email: jentery@uvic.ca
author: Jentery Sayers
twitter_username: jenterysayers
github_username: jentery
github_source: jentery

# Put your ga tracking code below
# google_analytics: 'UA-XXXXXXXX-X'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/articles/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Notes
    url: /notes/
    desc: notes for the seminar
  - title: Outline
    url: /outline
    desc: outline for the seminar
  - title: PDF
    url: /cspt500.pdf
    desc: pdf of the course outline 

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate